version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge